### PR TITLE
Enhancement - Ability to check status and not waiting for query completion

### PR DESCRIPTION
**Pull request by ignacioblit**

### CODE REVIEW

**Comment by ignacioblit** [comment]
Any updates?

**Comment by ghdna** [comment]
Sorry, I’m at reinvent this week. But will surely look at it over this
weekend.

**Comment by infinitewhile** [comment]
👍  - Any news on this PR? We're really interested in the work being done here. We'd like to use it in conjunction with step functions, firing off the query to return to it later. Cheers!

**Comment by nathanbrock** [comment]
👍  - Any news on this PR? We’re really interested in the work being done here. We’d like to use it in conjunction with step functions, firing off the query to return to it later. Cheers!

**Comment by ghdna** [comment]
I apologize for my tardiness on this one but I'll carve our time this week for this. Thanks for reminding me.

**Pull request merged**
