### PR TITLE
Allow config to include encryption

### PR DESCRIPTION
**Pull request by studmanho**
To be able to ass kms keys and encryption type, the config needed to be modified.

### CODE REVIEW

**Comment by studmanho** [comment]
Will this get merged in?

**Comment by studmanho** [comment]
I updated this to bump the package patch version. I wanted to kick of a new npm version so I can get the artifact

**Comment by ghdna** [comment]
I'll test it and merge the PR. Could you also update the readme docs to include the new params for encryption please?

**Comment by studmanho** [comment]
I made some changes to the README and I updated the code to make it optional in athenaExpress.js. Take a look

**Comment by ghdna** [comment]
Thanks. I'll test it when I get home today.

**Comment by studmanho** [comment]
How did it look?

**Comment by ghdna** [comment]
Updating readme. Currently shows `KmsKey` as an independent parameter.

**Pull request merged**
